project:
  name: taskcat-was-on-aws
  regions:
  - ca-central-1
  package_lambda: false
tests:
  default:
    template: ./templates/ibm-liberty-new-eks.template.yaml
    parameters:
      EKSClusterName: $[taskcat_project_name]
      SetupNewECR: "False"
      AcceptLicense: "Accept: Proceed with the installation"
      LicenseEdition: "IBM WebSphere Application Server"
      LicenseProductEntitlementSource: "Standalone"
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: ca-central-1
      QSS3KeyPrefix: $[taskcat_project_name]/
