apiVersion: v1
kind: Service
metadata:
  name: LOADBALANCER_NAME
  namespace: APPLICATION_NAMESPACE
spec:
  selector:
    app: APPLICATION_NAME
  ports:
  - name: https
    port: 443
    targetPort: 9443
  type: LoadBalancer
