// Include any postdeployment steps here, such as steps necessary to test that the deployment was successful. If there are no postdeployment steps, leave this file empty.

== Postdeployment steps

After deployment, validate the Quick Start deployment. If an application was deployed, also deploy the License Service.


=== Deployment validation

* If you selected to deploy the sample or a custom application
+
. Launch the application. From the *Outputs* tab of the main stack, click the value of the _AppEndpoint_ key.
. Deploy <<_license_service>>.
* If you did not deploy an application, check the *Outputs* tab of the main stack.

For general information about your deployment, see the <<#_how_do_i_get_information_about_my_deployment>> FAQ. If the deployment failed, see <<#_troubleshooting>>.

=== License Service

https://www.ibm.com/docs/SSHKN6/license-service/1.x.x/standalone-LS.html[Deploy License Service] on your Kubernetes cluster. License Service is required to measure and track license use of IBM Containerized Software such as {partner-product-short-name} Operator. Manual license measurements are not allowed.
