== Predeployment steps

Before you launch the {partner-product-short-name} Partner Solution, complete the following.

//TODO Marcia to spell these out: Identity and Access Management (IAM) permissions in your AWS account, and familiarize yourself with AWS services and AWS Command Line Interface (AWS CLI)

=== Check your license

Confirm that you have a license that entitles you to use {partner-product-short-name}. Refer to <<#_costs_and_licenses>> earlier in this guide.

=== Download and configure the Kubernetes CLI

Download and configure the Kubernetes CLI so that you can manage deployed applications and resources with `kubectl` commands. For more information, refer to https://docs.aws.amazon.com/eks/latest/userguide/install-kubectl.html[Installing or updating kubectl^].

=== (Optional) Note the ARNs that need to access the EKS cluster

By default, you can access the EKS cluster from the boot node only. If you want to enable direct access to the EKS cluster, prepare a list of IAM entity Amazon Resource Names (ARNs) that need to have this access. When you deploy this solution, you'll enter those ARNS in a comma-delimited list in the parameter *Additional EKS administrator ARNs (IAM users or roles)*.

For more information, refer to <<#_how_do_i_connect_to_the_eks_cluster>> later in this guide.

//TODO Marcia, Remember to align this guidance with that parameter description.

//TODO Marcia to spell out product names, check links & cross refs throughout doc.