//Include any predeployment steps here, such as signing up for a Marketplace AMI or making any changes to a partner account. If there are no predeployment steps, leave this file empty.

== Predeployment steps

Before you launch the Quick Start, see the https://fwd.aws/rA69w?[AWS Quick Start General Information Guide]. You need an AWS account, IAM permissions, and familarity with AWS services and the AWS CLI.

Also, complete the following predeployment steps.

=== Existing license

Confirm that you have a valid license to use {partner-product-short-name} Operator. See <<#_costs_and_licenses>>.


=== Resource quotas

This deployment uses the resource quotas in <<#_table1>>. If necessary, request https://console.aws.amazon.com/servicequotas[service quota increases].

[#_table1]
.Deployment resource quotas
[cols="1,1"]
|===
|Resource |This deployment uses

// Space needed to maintain table headers
|VPCs | 1
|VPC subnets | 4
|Elastic IP addresses | 1
|Security groups | 3
|AWS Identity and Access Management (IAM) roles | 4
|Classic Load Balancer | 2
|EC2 Instance, t2.micro | 1
|EC2 Instance, m5.large | 3
|ECR repositories | 1
|SSM associations | 2
|Lambda functions | 2
|EKS clusters | 1
|===


=== Kubernetes CLI

Download and configure the https://docs.aws.amazon.com/eks/latest/userguide/install-kubectl.html[Kubernetes command-line interface (CLI)] so that you can manage deployed applications and resources with `kubectl` commands.


=== EKS cluster access

When you build the CloudFormation stack, https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_manage-attach-detach.html[provide your IAM user ARN] in the _AdditionalEKSAdminArns_ parameter.

Any IAM entity ARNs in this parameter can access the EKS cluster during the {partner-product-short-name} Operator deployment. IAM entity ARNs are specified in a comma-delimited list.

Note that you might need to start the boot node to connect to the EKS cluster. 

[TIP]
To monitor progress during deployment, view <<#_cloudwatch_log_streams>>.
