== Predeployment steps

Before you launch the {partner-product-short-name} Partner Solution, complete the following.

=== Set up your AWS account

Set up AWS Identity and Access Management (IAM) permissions in your AWS account, and familiarize yourself with AWS services and AWS Command Line Interface (AWS CLI). Consider making the IAM users or roles administrators of the EKS cluster, and set up the Kubernetes CLI to manage your cluster from the command line.

For more information, refer to the https://fwd.aws/rA69w?[AWS Partner Solution General Information Guide^]. 

//TODO Vinod, Does the second sentence basically repeat what we say later under "Download and configure the Kubernetes CLI"? 

//TODO Vinod, Can IAM users and roles be made administrators of the EKS cluster prior to deployment?

//TODO Vinod, Which AWS services are we referring to in the first sentence? I suggest that we delete this "Set up your AWS account" section. We don't normally include it any more since this content is covered in the General Info Guide.

=== Check your license

Confirm that you have a license that entitles you to use {partner-product-short-name}. Refer to <<#_costs_and_licenses>> earlier in this guide.

=== Check your resource quotas

Check the resource quotas listed in <<#_resource_table>>. If necessary, request https://console.aws.amazon.com/servicequotas[service quota increases]. 

[#_resource_table]
.Deployment resource quotas
[cols="1,1"]
|===
|Resource |This deployment uses

// Space needed to maintain table headers
|VPCs | 1
|VPC subnets | 4
|Elastic IP addresses | 1
|Security groups | 3
|IAM roles | 4
|Classic Load Balancer | 1
|EC2 instance, t2.micro | 1
|EC2 instance, m5.large | 2
|ECR repositories | 1
|SSM associations | 2
|Lambda functions | 2
|EKS clusters | 1
|===

//TODO Vinod, I haven't seen a resource table like this or references to quotas in a deployment guide in a long time. We cover the topic at a high level in our General Info Guide. Is there a special need to include this section in this case?

=== Download and configure the Kubernetes CLI

Download and configure the Kubernetes CLI so that you can manage deployed applications and resources with `kubectl` commands. For more information, refer to https://docs.aws.amazon.com/eks/latest/userguide/install-kubectl.html[Installing or updating kubectl^].

//TODO Vinod, Does this section basically repeating what we said earlier about the Kubernetes CLI (under "Set up your AWS account")? Please revise to avoid redundancy.

=== (Optional) Note the ARNs that need to access the EKS cluster

By default, you can access the EKS cluster from the boot node only. If you want to enable direct access to the EKS cluster, prepare a list of IAM entity Amazon Resource Names (ARNs) that need to have this access. When you deploy this solution, you'll enter those ARNS in a comma-delimited list in the parameter *Additional EKS administrator ARNs (IAM users or roles)*.

For more information, refer to <<#_how_do_i_connect_to_the_eks_cluster>> later in this guide.

//TODO Marcia, Remember to align this guidance with that parameter description.

=== (Optional) Prepare to monitor your deployment

During deployment, you can monitor progress by viewing log data. To learn how to do this, refer to <<#_cloudwatch_log_streams>> later in this guide.

//TODO Marcia to spell out product names, check links & cross refs throughout doc.