For troubleshooting common Partner Solution issues, refer to the https://fwd.aws/rA69w?[AWS Partner Solution General Information Guide^] and https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/troubleshooting.html[Troubleshooting CloudFormation^].

For information on using this solution after it's deployed, refer to the https://fwd.aws/Q9vrR?[{partner-product-name} Partner Solution Operational Guide^].

== Customer support

For {partner-product-short-name} issues, open a case (support ticket) with IBM Support as follows:

. Go to the https://www.ibm.com/mysupport/s/topic/0TO500000001DQQGA2/websphere-application-server[WebSphere Application Server^] or https://www.ibm.com/mysupport/s/[Let's troubleshoot^] page, and choose *Open a case*.
. In the ticket, describe the error.
+
Include information that can help IBM Support determine the cause of the error. For example, you might describe your cluster configuration and the component that is failing or having issues. If the error is difficult to describe, provide a screenshot of the error. 

To learn how to find deployment logs, refer to the https://fwd.aws/Q9vrR?[{partner-product-name} Partner Solution Operational Guide^].

To learn how to use MustGather to collect information for a support ticket, refer to https://www.ibm.com/docs/SSEQTP_liberty/opr/ae/t-troubleshooting.html#t-troubleshooting__must-gather[Gathering information about clusters with MustGather^].


== Resources

* https://www.ibm.com/docs/SSEQTP_liberty/opr/ae/cfg-t-viewstatus.html[Viewing operator application status^]
* https://www.ibm.com/docs/SSEQTP_liberty/opr/ae/t-troubleshooting.html[Troubleshooting WebSphere Liberty operators^]
* https://fwd.aws/Q9vrR?[{partner-product-name} Partner Solution Operational Guide^]