AWSTemplateFormatVersion: "2010-09-09"
Description: "This template deploys a WebSphere Liberty operator and application into a new EKS cluster in a new VPC. (qs-1tdrllesf)"
Metadata:
  QuickStartDocumentation:
    EntrypointName: Deploy with an application
    Order: 1
  LICENSE: Apache License, Version 2.0
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: EKS configuration
        Parameters:
          - EKSClusterName
          - SetupNewECR
          - AdditionalEKSAdminArns
          - AvailabilityZones
      - Label:
          default: Application configuration
        Parameters:
          - DeployApp
          - AppContainerImageURL
          - AppName
          - AppNamespace
          - AppReplicas
      - Label:
          default: License
        Parameters:
          - LicenseEdition
          - LicenseProductEntitlementSource
          - AcceptLicense
      - Label:
          default: AWS Partner Solution configuration
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix
          - QSS3BucketRegion
    ParameterLabels:
      AcceptLicense:
        default: Accept (https://ibm.biz/was-license)
      AppContainerImageURL:
        default: Custom application image
      AppName:
        default: Application name
      AppNamespace:
        default: Application namespace
      AppReplicas:
        default: Application replicas
      DeployApp:
        default: Deploy application
      EKSClusterName:
        default: EKS cluster name
      LicenseEdition:
        default: Edition
      LicenseProductEntitlementSource:
        default: Product entitlement source
      QSS3BucketName:
        default: Partner Solution S3 bucket name
      QSS3BucketRegion:
        default: Partner Solution S3 bucket Region
      QSS3KeyPrefix:
        default: Partner Solution S3 key prefix
      AdditionalEKSAdminArns:
        default: Additional EKS administrator ARNs 
      SetupNewECR:
        default: Set up new ECR
      AvailabilityZones:
        default: Availability Zones

Parameters:
  AvailabilityZones:
    Description: Availability Zones to use for the subnet in the new VPC. You must select 2 Availability Zones.
    Type: List<AWS::EC2::AvailabilityZone::Name>
  AcceptLicense:
    Type: String
    AllowedValues: ["Accept: Proceed with the installation", "Decline: Exit without installing"]
    Description: >-
      I accept the terms on the license agreement corresponding to the version of IBM program
      in the application container by setting this value to true. See https://ibm.biz/was-license
      for the license agreement applicable to this IBM program. You must accept the license if you are deploying sample or custom application.
    ConstraintDescription: You must accept the license (https://ibm.biz/was-license) to proceed with installation.
  AppContainerImageURL:
    Type: String
    Description: >-
      For example, icr.io/appcafe/open-liberty/samples/getting-started. This value is only required when "Deploy application" is set to "Custom". The image must be accessible without any credentials.
    AllowedPattern: ^(?:(?=[^:\/]{4,253})(?!-)[a-zA-Z0-9-]{1,63}(?<!-)(?:\\.(?!-)[a-zA-Z0-9-]{1,63}(?<!-))*(?::[0-9]{1,5})?/)?((?![._-])(?:[a-z0-9._-]*)(?<![._-])(?:/(?![._-])[a-z0-9._-]*(?<![._-]))*)(?::(?![.-])[a-zA-Z0-9_.-]{1,128})?$
    ConstraintDescription: The value must be a valid application image path. For example, icr.io/appcafe/open-liberty/samples/getting-started
  AppName:
    Type: String
    Default: "websphereliberty-app-sample"
    Description: Name of application to deploy.
    AllowedPattern: (?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*
    ConstraintDescription: The name must start with a letter and can only contain lowercase letters, numbers, hyphens, underscores, periods and forward slashes.
  AppNamespace:
    Type: String
    Default: "default"
    Description: Namespace in the EKS cluster where the application will be deployed.
    AllowedPattern: (?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*
    ConstraintDescription: The name must start with a letter and can only contain lowercase letters, numbers, hyphens, underscores, periods and forward slashes.
  AppReplicas:
    Type: Number
    MinValue: 1
    Default: 2
    Description: Number of application replicas (minimum 1).
  DeployApp:
    Type: String
    AllowedValues: [ "Sample", "Custom" ]
    Default: "Sample"
    Description: Deploy sample or custom application or skip application deployment. Details on sample application is available at https://github.com/OpenLiberty/sample-getting-started.
  EKSClusterName:
    Type: String
    Description: Name of the new EKS cluster (length 2—250 characters). The name must start with a letter and contain only lowercase letters, numbers, hyphens, underscores, periods, or forward slashes.
    MinLength: 2
    MaxLength: 250
    AllowedPattern: (?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*
    ConstraintDescription: The name must start with a letter and contain only lowercase letters, numbers, hyphens, underscores, periods, or forward slashes.
  LicenseEdition:
    Type: String
    AllowedValues: ["IBM WebSphere Application Server", "IBM WebSphere Application Server Liberty Core", "IBM WebSphere Application Server Network Deployment"]
    Description:  Product edition.
  LicenseProductEntitlementSource:
    Type: String
    AllowedValues: ["Standalone", "IBM WebSphere Hybrid Edition", "IBM Cloud Pak for Applications", "IBM WebSphere Application Server Family Edition"]
    Description: Entitlement source for the product. Select "Standalone" if the entitlement source is IBM WebSphere Application Server, IBM WebSphere Application Server Liberty Core, or IBM WebSphere Application Server Network Deployment.
  SetupNewECR:
    Type: String
    AllowedValues: ["Yes", "No"]
    Default: "Yes"
    Description: Choose No if you do not want to set up a new private ECR named <EKS cluster name>-ecr.
  QSS3BucketName:
    MinLength: 3
    MaxLength: 63
    Type: String
    Description: >-
      Name of the S3 bucket for your copy of the deployment assets. Keep the default
      name unless you are customizing the template. Changing the name updates code 
      references to point to a new location.
    AllowedPattern: ^[0-9a-z]+([0-9a-z-\.]*[0-9a-z])*$
    ConstraintDescription: >-
      The S3 bucket name can include numbers, lowercase letters, 
      and hyphens (-), but it cannot start or end with a hyphen.
    Default: aws-quickstart
  QSS3KeyPrefix:
    Type: String
    Description: >-
      S3 key prefix that is used to simulate a folder for your copy of the 
      deployment assets. Keep the default prefix unless you are customizing 
      the template. Changing the prefix updates code references to point to 
      a new location.
    AllowedPattern: ^([0-9a-zA-Z!-_\.\*'\(\)/]+/)*$
    ConstraintDescription: >-
      The S3 key prefix can include numbers, lowercase letters, uppercase letters, 
      hyphens (-), underscores (_), periods (.), asterisks (*), single quotes ('),
      open parenthesis ((), close parenthesis ()), and forward slashes (/). End the
      prefix with a forward slash.
    Default: quickstart-ibm-liberty-eks/
  QSS3BucketRegion:
    Type: String
    Description: >-
      AWS Region where the S3 bucket (QSS3BucketName) is hosted. Keep 
      the default Region unless you are customizing the template. Changing the Region 
      updates code references to point to a new location. When using your own bucket, 
      specify the Region.
    Default: us-east-1
  AdditionalEKSAdminArns:
    Default: ""
    Description: >-
      "(Optional) One or more IAM user or role ARNs to be granted administrative access to the new EKS cluster. By default, you can access the EKS cluster from boot node only. To enter multiple ARNs, use a comma-delimited list. Example: arn:aws:iam::012345678910:user/myid@example.com,
      arn:aws:iam::012345678910:user/otherid@example.com."
    Type: String

Conditions:
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, aws-quickstart]
  SetupECR: !Equals [!Ref SetupNewECR, "Yes"]
  DeploySample: !Equals [!Ref DeployApp, Sample]

Rules:
  RequireAcceptLicense:
    Assertions:
      - Assert: !Equals [!Ref AcceptLicense, "Accept: Proceed with the installation"]
        AssertDescription: In order to proceed with installation, you must accept the license.
  RequireImageWhenCustom:
    RuleCondition: !Equals [!Ref DeployApp, Custom]
    Assertions:
      - Assert: !Not [!Equals [!Ref AppContainerImageURL, ""]]
        AssertDescription: You must provide an image when deploying a custom application.

