AWSTemplateFormatVersion: 2010-09-09
Description: This template creates a new ECR. (qs-1tdrmii9e)
Metadata:
  ParameterLabels:
      ECRName:
        default: ECR Name
Parameters:
  ECRName:
    Type: String
    Description: Name for the new ECR. The name must start with a letter and can only contain lowercase letters, numbers, hyphens, underscores, periods and forward slashes.
Resources:
  IBMLibertyNewECRStack:
    Type: AWS::ECR::Repository
    Properties:  
      RepositoryName: !Ref ECRName
Outputs:
  ECRName:
    Description: ECR name
    Value: !Ref ECRName
  ECRArn:
    Description: ECR ARN
    Value: !GetAtt IBMLibertyNewECRStack.Arn
  ECRRepositoryUri:
    Description: ECR URI
    Value: !GetAtt IBMLibertyNewECRStack.RepositoryUri
