apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-websphere-liberty
  namespace: operators
spec:
  installPlanApproval: Automatic
  name: ibm-websphere-liberty
  source: ibm-operator-catalog
  sourceNamespace: olm